added new phrases on 2.4.6-p4
magento/language-ja_JP pull request #1
Opened 2024-02-14 09:10 UTC by HirokazuNishi

Added phrases that were added on 2.4.6-p4 (Auto generated coupon code)

2024-03-28 08:38 UTC, nozokada commented on ja_JP.csv
> +"Code Quantity Limit","クーポン数量上限値"
```suggestion
"Code Quantity Limit","クーポン数量の上限"
```

2024-03-28 08:39 UTC, nozokada commented on ja_JP.csv
> +"Coupon quantity should be less than or equal to the coupon quantity in the store configuration.","クーポンの数量はストア設定値以下でなければなりません。"
```suggestion
"Coupon quantity should be less than or equal to the coupon quantity in the store configuration.","クーポンの数量はストア設定のクーポンの数量以下でなければなりません。"
```

2024-03-28 08:42 UTC, nozokada requested changes
いつもありがとうございます。少しだけ修正をお願いいたします。

2024-03-29 04:31 UTC, HirokazuNishi commented
@nozokada 修正しました。

2024-04-01 04:31 UTC, nozokada approved these changes

2024-04-01 04:31 UTC, merged